version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-server-goProject
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - '5433:5432'
    volumes: 
      - ./postgres/data:/var/lib/postgresql/data
    security_opt:
      - no-new-privileges:true